default:
  outputs:

    dev:
      type: postgres
      threads: 1
      host: "{{ env_var('DWH_POSTGRES_HOST', 'localhost') }}"
      port: 5432
      user: "{{ env_var('DWH_POSTGRES_ADMIN') }}"
      pass: "{{ env_var('DWH_POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('DWH_POSTGRES_DB') }}"
      schema: "{{ env_var('DWH_POSTGRES_PRS_SCHEMA', 'public') }}"

  target: dev
