import os

DWH_POSTGRES_ADMIN = os.environ['DWH_POSTGRES_ADMIN']
DWH_POSTGRES_PASSWORD = os.environ['DWH_POSTGRES_PASSWORD']
DWH_POSTGRES_DB = os.environ['DWH_POSTGRES_DB']
DWH_POSTGRES_HOST = os.environ['DWH_POSTGRES_HOST']


MB_ADMIN_FIRST_NAME = os.environ['MB_ADMIN_FIRST_NAME']
MB_ADMIN_LAST_NAME = os.environ['MB_ADMIN_LAST_NAME']
MB_ADMIN_EMAIL = os.environ['MB_ADMIN_EMAIL']
MB_ADMIN_PASSWORD = os.environ['MB_ADMIN_PASSWORD']

METABASE_HOST='http://metabase:3000'
SETUP_TOKEN_ENDPOINT='api/session/properties'
SETUP_ADMIN_ENDPOINT='api/setup'
SETUP_DATABASE_ENDPOINT='api/database'
NEW_USER_ENDPOINT='api/user'

SETUP_TOKEN_URL = f'{METABASE_HOST}/{SETUP_TOKEN_ENDPOINT}'
SETUP_ADMIN_URL = f'{METABASE_HOST}/{SETUP_ADMIN_ENDPOINT}'
SETUP_DATABASE_URL = f'{METABASE_HOST}/{SETUP_DATABASE_ENDPOINT}'
NEW_USER_URL = f'{METABASE_HOST}/{NEW_USER_ENDPOINT}'